/* eslint-disable no-undef */
const dataMembers = [
  {
    id: 1,
    name: "Adzana Shaliha",
    nikcName: "Ashel",
    kabesha: "./src/assets/images/kabesha/kabesha-ashel.jpg",
    page: "/ashel",
  },
  {
    id: 2,
    name: "Alya Amanda",
    nikcName: "Alya",
    kabesha: "./src/assets/images/kabesha/kabesha-alya.jpg",
    page: "/alya",
  },
  {
    id: 3,
    name: "Amanda Sukma",
    nikcName: "Amanda",
    kabesha: "./src/assets/images/kabesha/kabesha-amanda.jpg",
    page: "/amanda",
  },
  {
    id: 4,
    name: "Anindya Ramadhani",
    nikcName: "Anindya",
    kabesha: "./src/assets/images/kabesha/kabesha-anindya.jpg",
    page: "/anindya",
  },
  {
    id: 5,
    name: "Angelina Christy",
    nikcName: "Christy",
    kabesha: "./src/assets/images/kabesha/kabesha-christy.jpg",
    page: "/christy",
  },
  {
    id: 6,
    name: "Aurellia",
    nikcName: "Lia",
    kabesha: "./src/assets/images/kabesha/kabesha-aurellia.jpg",
    page: "/lia",
  },
  {
    id: 7,
    name: "Azizi Asadel",
    nikcName: "Zee",
    kabesha: "./src/assets/images/kabesha/kabesha-zee.jpg",
    page: "/zee",
  },
  {
    id: 8,
    name: "Callista Alifia",
    nikcName: "Callie",
    kabesha: "./src/assets/images/kabesha/kabesha-callie.jpg",
    page: "/callie",
  },
  {
    id: 9,
    name: "Cathleen Nixie",
    nikcName: "Cathy",
    kabesha: "./src/assets/images/kabesha/kabesha-cathy.jpg",
    page: "/cathy",
  },
  {
    id: 10,
    name: "Celline Thefani",
    nikcName: "Elin",
    kabesha: "./src/assets/images/kabesha/kabesha-elin.jpg",
    page: "/elin",
  },
  {
    id: 11,
    name: "Chelsea Davina",
    nikcName: "Chelsea",
    kabesha: "./src/assets/images/kabesha/kabesha-chelsea.jpg",
    page: "/chelsea",
  },
  {
    id: 12,
    name: "Cornelia Vanisa",
    nikcName: "Oniel",
    kabesha: "./src/assets/images/kabesha/kabesha-oniel.jpg",
    page: "/oniel",
  },
  {
    id: 13,
    name: "Cynthia Yaputera",
    nikcName: "Cynthia",
    kabesha: "./src/assets/images/kabesha/kabesha-cynthia.jpg",
    page: "/cynthia",
  },
  {
    id: 14,
    name: "Dena Natalia",
    nikcName: "Danella",
    kabesha: "./src/assets/images/kabesha/kabesha-dena.jpg",
    page: "/danella",
  },
  {
    id: 15,
    name: "Desy Natalia",
    nikcName: "Daisy",
    kabesha: "./src/assets/images/kabesha/kabesha-daisy.jpg",
    page: "/daisy",
  },
  {
    id: 16,
    name: "Febriola Sinambela",
    nikcName: "Olla",
    kabesha: "./src/assets/images/kabesha/kabesha-olla.jpg",
    page: "/olla",
  },
  {
    id: 17,
    name: "Feni Fitriyanti",
    nikcName: "Feni",
    kabesha: "./src/assets/images/kabesha/kabesha-feni.jpg",
    page: "/feni",
  },
  {
    id: 18,
    name: "Fiony Alveria",
    nikcName: "Fiony",
    kabesha: "./src/assets/images/kabesha/kabesha-fiony.jpg",
    page: "/fiony",
  },
  {
    id: 19,
    name: "Flora Shafiq",
    nikcName: "FLora",
    kabesha: "./src/assets/images/kabesha/kabesha-flora.jpg",
    page: "/flora",
  },
  {
    id: 20,
    name: "Freya Jayawardana",
    nikcName: "Freya",
    kabesha: "./src/assets/images/kabesha/kabesha-freya.jpg",
    page: "/freya",
  },
  {
    id: 21,
    name: "Gabriela Abigail",
    nikcName: "Ella",
    kabesha: "./src/assets/images/kabesha/kabesha-ella.jpg",
    page: "/ella",
  },
  {
    id: 22,
    name: "Gendis Mayrannisa",
    nikcName: "Gendis",
    kabesha: "./src/assets/images/kabesha/kabesha-gendis.jpg",
    page: "/gendis",
  },
  {
    id: 23,
    name: "Gita Sekar Andarini",
    nikcName: "Gita",
    kabesha: "./src/assets/images/kabesha/kabesha-gita.jpg",
    page: "/gita",
  },
  {
    id: 24,
    name: "Grace Octaviani",
    nikcName: "Gracie",
    kabesha: "./src/assets/images/kabesha/kabesha-gracie.jpg",
    page: "/gracie",
  },
  {
    id: 25,
    name: "Greesella Adhalia",
    nikcName: "Greesel",
    kabesha: "./src/assets/images/kabesha/kabesha-greesel.jpg",
    page: "/greesel",
  },
  {
    id: 26,
    name: "Helisma Putri",
    nikcName: "Eli",
    kabesha: "./src/assets/images/kabesha/kabesha-eli.jpg",
    page: "/eli",
  },
  {
    id: 27,
    name: "Indah Cahya",
    nikcName: "Indah",
    kabesha: "./src/assets/images/kabesha/kabesha-indah.jpg",
    page: "/indah",
  },
  {
    id: 28,
    name: "Indira Seruni",
    nikcName: "Indira",
    kabesha: "./src/assets/images/kabesha/kabesha-indira.jpg",
    page: "/indira",
  },
  {
    id: 29,
    name: "Jeane Victoria",
    nikcName: "Jeane",
    kabesha: "./src/assets/images/kabesha/kabesha-jeane.jpg",
    page: "/jeane",
  },
  {
    id: 30,
    name: "Jessica Chandra",
    nikcName: "Jessi",
    kabesha: "./src/assets/images/kabesha/kabesha-jessica.jpg",
    page: "/jessi",
  },
  {
    id: 31,
    name: "Jesslyn Elly",
    nikcName: "Lyn",
    kabesha: "./src/assets/images/kabesha/kabesha-lyn.jpg",
    page: "/lyn",
  },
  {
    id: 32,
    name: "Kathrina Irene",
    nikcName: "Kathrina",
    kabesha: "./src/assets/images/kabesha/kabesha-kathrina.jpg",
    page: "/kathrina",
  },
  {
    id: 33,
    name: "Lulu Salsibla",
    nikcName: "Lulu",
    kabesha: "./src/assets/images/kabesha/kabesha-lulu.jpg",
    page: "/lulu",
  },
  {
    id: 34,
    name: "Marsha Lenathea",
    nikcName: "Marsha",
    kabesha: "./src/assets/images/kabesha/kabesha-marsha.jpg",
    page: "/marsha",
  },
  {
    id: 35,
    name: "Michelle Alexandra",
    nikcName: "Michie",
    kabesha: "./src/assets/images/kabesha/kabesha-michie.jpg",
    page: "/michie",
  },
  {
    id: 36,
    name: "Mutiara Azzahra",
    nikcName: "Muthe",
    kabesha: "./src/assets/images/kabesha/kabesha-muthe.jpg",
    page: "/muthe",
  },
  {
    id: 37,
    name: "Raisha Syifa",
    nikcName: "Raisha",
    kabesha: "./src/assets/images/kabesha/kabesha-raisya.jpg",
    page: "/raisha",
  },
  {
    id: 38,
    name: "Reva Fidela",
    nikcName: "Adel",
    kabesha: "./src/assets/images/kabesha/kabesha-adel.jpg",
    page: "/adel",
  },
  {
    id: 39,
    name: "Shani Indira Natio",
    nikcName: "Shani",
    kabesha: "./src/assets/images/kabesha/kabesha-shani.jpg",
    page: "/shani",
  },
  {
    id: 40,
    name: "Shania Gracia",
    nikcName: "Gracia",
    kabesha: "./src/assets/images/kabesha/kabesha-gracia.jpg",
    page: "/gracia",
  },
  {
    id: 41,
    name: "Yessica Tamara",
    nikcName: "Chika",
    kabesha: "./src/assets/images/kabesha/kabesha-chika.jpg",
    page: "/chika",
  },
];

export default dataMembers;
